name: Build Space Travel Time Calculator

on:
  push:
    branches: [ master ]
    paths:
    - 'space-travel-time-calculator/**/*'
    - '.github/workflows/space-calc.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'space-travel-time-calculator/**/*'
    - '.github/workflows/space-calc.yml' 

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./space-travel-time-calculator

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: go get fyne.io/fyne/v2
    - name: make
      run: make
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'push' }}
      with:
        name: travelcalc
        path: |
          space-travel-time-calculator/travelcalc.exe
          space-travel-time-calculator/stars.dat